[2020-06-03 18:00:11,922] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_dag.upload_percentage 2020-06-03T12:27:10.476700+00:00 [queued]>
[2020-06-03 18:00:11,932] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_dag.upload_percentage 2020-06-03T12:27:10.476700+00:00 [queued]>
[2020-06-03 18:00:11,932] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 18:00:11,932] {taskinstance.py:880} INFO - Starting attempt 1 of 4
[2020-06-03 18:00:11,932] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 18:00:11,940] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): upload_percentage> on 2020-06-03T12:27:10.476700+00:00
[2020-06-03 18:00:11,943] {standard_task_runner.py:53} INFO - Started process 26438 to run task
[2020-06-03 18:00:11,981] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag.upload_percentage 2020-06-03T12:27:10.476700+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-03 18:00:15,565] {taskinstance.py:1145} ERROR - name 'csv' is not defined
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/covid_dag.py", line 66, in upload_percentage
    reader_file = csv.reader(input_file)
NameError: name 'csv' is not defined
[2020-06-03 18:00:15,570] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-03 18:00:21,919] {logging_mixin.py:112} INFO - [2020-06-03 18:00:21,917] {local_task_job.py:103} INFO - Task exited with return code 1
